#!/bin/bash

# Store the PATH variable in a variable
PATHVAR=$PATH

# Count the number of directories in the PATH variable
DIRCOUNT=$(echo $PATHVAR | tr ':' '\n' | wc -l)

# Print the result
echo "The number of directories in the PATH variable is $DIRCOUNT"
